### ISSUE TITLE
Copy repo from personal account to yiiext

### ISSUE THREAD

**Issue by stamm** [yiiext/core#2]
Hello, Cebe.
How I could copy existing repo from my personal account to yiiext repo?

**Comment by cebe** [comment]
what repo is it?

I think it is the right way to ask here and I'll do it. We haven't got a workflow for that yet. What do you think @samdark?

**Comment by samdark** [comment]
I think that's the right way to do it. Additionally a guide to add repository will be very handy.

**Comment by samdark** [comment]
Oww… hitting "Comment & Close" every time I'm submitting a comment :)

**Comment by stamm** [comment]
So, add my component to shorter url with goo.gl: https://github.com/Stamm/yii.shorturl

**Comment by samdark** [comment]
Is it OK if I'll add new repository and you'll use it as a master for your own one?

**Comment by cebe** [comment]
I think forking it is best practise on github. Will check that just now.

**Comment by cebe** [comment]
done. forked it to https://github.com/yiiext/shorturl-component

Please add a Readme file soon.

**Comment by samdark** [comment]
Hmm… how Stamm should work with it now?
1. How to keep yiiext version up to date?
2. Which repo to use for bug reports and feature requests?

**Comment by cebe** [comment]
I think work should be done on the yiiext repo, just like it's done for all other extensions.
bugs and wiki should be on yiiext.
I asked at github support what's the best way to do such things in the future. I think the original repo can be deleted so no sync work has to be done.

**Comment by stamm** [comment]
Cebe, thanks. I remove my repo, add readme.
