### ISSUE TITLE
Transfer repo to yiiext

### ISSUE THREAD

**Issue by MrMaxB** [yiiext/core#3]
I have push permissions, but don`t know how to add my repo to yiiext.
Link: https://github.com/DeusModus/yii-ext-reversed-pagination
Can any one help me?

**Comment by samdark** [comment]
Looks like only repo owners can create new repositories. Is it OK if I'll add new repo here and you'll use it as a master for your own one?

**Comment by cebe** [comment]
I think forking it is best practise on github. Will check that just now.

**Comment by cebe** [comment]
done. https://github.com/yiiext/reversed-pagination

please adjust your file structure, so that your files are on repo root.
