### ISSUE TITLE
yii mirros isn't updating anymore

### ISSUE THREAD

**Issue by samdark** [yiiext/core#4]
Looks like yii mirros isn't updated anymore.

**Comment by cebe** [comment]
Yes, I need to update the script to notify me on errors. There is sometime a problem with commit authors, once the name is given without @gmail.com sometimes it is with @gmail.com, so I now updated the authors.txt to have both names matched.

**Comment by cebe** [comment]
Updated that script to send me an email if yii mirror update fails
