### ISSUE TITLE
TinyButStrong template engine extension for Yii

### ISSUE THREAD

**Issue by maortega** [yiiext/core#5]
Hello, here is an extension to use a TinyButStrong renderer:

https://github.com/maortega/tbs_yii_ext

I hope you find it useful.

**Comment by samdark** [comment]
Do you want to join YiiExt and merge your extension into it?

**Comment by maortega** [comment]
Sure

**Comment by samdark** [comment]
Done. Now you're part of the team. Repository is here: https://github.com/yiiext/tinybutstrong-renderer

Please check other extensions for a clue about proper readme formats, changelog etc. These are needed to generate info for http://yiiext.github.com/

**Comment by cebe** [comment]
This reminds me about yiiext/yiiext.github.com#12 ... need to fix that to generate yiiext.github.com pages...

**Comment by maortega** [comment]
Ok, thanks.
